services:
  - type: web
    name: aethowave-api
    env: python
    plan: free
    runtime: python-3.11
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && pip install --upgrade yt-dlp
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 2
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
